const ActionType = {
  USERS_PUT_USER:"USERS_PUT_USER",
  USERS_PUT_ISAUTH:"USERS_PUT_ISAUTH",
  APP_REQUEST_GET_ACCOUNTS_VK:"APP_REQUEST_GET_ACCOUNTS_VK",
  COPY_DATA_ACCOUNTS_VK:"COPY_DATA_ACCOUNTS_VK",
  LOGIN_DATA_REGISTRATION_VK:"LOGIN_DATA_REGISTRATION_VK",
  APP_SIDE_MENU:"APP_SIDE_MENU",
  APP_PAGES_SCREEN:"APP_PAGES_SCREEN",
  APP_HEADER_HIDDEN_CHANGE:"APP_HEADER_HIDDEN_CHANGE",
  POPUP_LOGIN_VISIBLE:"POPUP_LOGIN_VISIBLE",
}

export default ActionType;